---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: alloy
spec:
  chart:
    spec:
      chart: alloy
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: alloy
      version: 1.x.x
  interval: 1m0s
  # https://github.com/grafana/alloy/tree/main/operations/helm/charts/alloy/values.yaml
  values:
    alloy:
      clustering:
        enabled: false
      extraPorts:
        - name: otlp-grpc
          port: 4317
          targetPort: 4317
          protocol: TCP

    controller:
      podLabels:
        pod-security.kubernetes.io/enforce: privileged
      type: daemonset
