---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  chart:
    spec:
      chart: tempo-distributed
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tempo
      version: 1.x
  interval: 1m0s
  # https://github.com/grafana/helm-charts/blob/main/charts/tempo-distributed/values.yaml
  values:
    global:
      dnsService: coredns
